-- =============================================================================
-- MARKAZ Home — seed (runs automatically after canonical migrations on reset).
--
-- Demo Auth users and demo domain data are NO LONGER created here. Writing the
-- Supabase Auth tables from SQL is not an officially supported operation
-- (Week 1.5, ADR-0009), so demo provisioning moved to a supported, idempotent,
-- production-guarded Admin-API script:
--
--     pnpm supabase:reset      # migrations + this (intentionally empty) seed
--     pnpm db:setup            # creates demo Auth users + demo domain data
--
-- Keep only schema-independent, Auth-independent setup below (currently none —
-- the realtime_counters 'demo' row is created by migration 05).
-- =============================================================================

-- (intentionally empty)
